# -*- encoding: utf-8 -*-
##############################################################################
#
# ERP Heritage
# Copyright (C) 2026 (https://www.erpheritage.com.au/)
#
##############################################################################
"""Sale order link to warehouse billing run."""
from odoo import fields, models


class SaleOrder(models.Model):
    _inherit = "sale.order"

    eh_log_warehouse_billing_run_id = fields.Many2one(
        "eh.log.warehouse.billing.run",
        string="Warehouse Billing Run",
        readonly=True,
        copy=False,
        help=(
            "Source billing run if this order was generated by the "
            "monthly warehouse billing engine."
        ),
    )
